### ISSUE TITLE
使用MWeb3 编译网站时出错

### ISSUE THREAD

**Issue by Gk0Wk** [Astrian/reflect-white-mweb-theme#18]
已设置所有必填项，Build的时候获得以下错误提示：

> ### Build Site Errors!
> Error Domain=MGTemplateEngineErrorDomain Code=3 ""ext_username" is not a valid variable" UserInfo={NSLocalizedDescription="ext_username" is not a valid variable}

不太清楚发生了什么

**Comment by Astrian** [comment]
笔名出现错误了，你填写的是什么？

**Comment by Gk0Wk** [comment]
正常的字符串`Sttot`:

<img width="175" alt="Screen Shot 2019-11-14 at 00 50 17" src="https://user-images.githubusercontent.com/16955102/68785196-c1790f00-0678-11ea-8c40-6b06a265d920.png">

**Comment by Astrian** [comment]
我后面看一下，感谢

**Comment by Astrian** [comment]
你好，这边我检查过编译没有问题。方便留一个即时通讯工具来即时诊断吗？
[这是我的 Telegram](https://t.me/astrian)，或者有其他联系方式吗？

**Comment by Gk0Wk** [comment]
Telegram我不太会用，不过你可以[加我一下](https://t.me/sttot)。麻烦了。
