### ISSUE TITLE
找不到图中评论和分享代码的区块

### ISSUE THREAD

**Issue by ZephyrDeng** [Astrian/reflect-white-mweb-theme#20]

**Comment by Astrian** [comment]
你好，这个问题应该是 MWeb 功能更新后出现的问题，我先去问问 MWeb 开发者是怎么回事……

**Comment by Astrian** [comment]
https://t.me/mwebapp/17253
确认是被拿掉了……
下个版本修复一下

**Comment by Astrian** [comment]
已在 1.0.3 更新中修复。
https://github.com/Astrian/reflect-white-mweb-theme/releases/tag/1.0.3
